#!/usr/bin/env bash

export PATH="$(dirname "$0"):$PATH"

cmd="$1"

case "$cmd" in
"" | list)
	licenses-list
	;;
get)
	licenses-get "$2"
	;;
update)
	licenses-update
	;;
-h | --help | help)
	cat <<EOF
usage: ${0##*/} [command | license-id]

commands:
  list   - list available licenses (local cache)
  get    - copy a license to LICENSE file
  update - download/sync all available licenses

shorthand:
  ${0##*/} <license-id>  (alias for get)

example usage:
  ${0##*/} update
  ${0##*/} list
  ${0##*/} mit
EOF
	exit 0
	;;
*)
	licenses-get "$cmd"
	;;
esac
