#!/usr/bin/env bash

# Set PATH to include the directory where the licenses-* scripts are located
export PATH="$(dirname "$0"):$PATH"

cmd="$1"

case "$cmd" in
"" | list)
    licenses-list
    ;;
get)
    licenses-get "$2"
    ;;
update)
    licenses-update
    ;;
-h | --help | help)
    cat <<EOF
usage: ${0##*/} <command>

commands:
  list   - list available licenses (local cache)
  get    - copy a license to LICENSE file
  update - download/sync all available licenses

example usage:
  ${0##*/} update
  ${0##*/} list
  ${0##*/} get MIT
EOF
    exit 0
    ;;
*)
    printf 'unknown command: %s\n' "$cmd" >&2
    exit 1
    ;;
esac
